In [19]:
from PIL import Image
import numpy as np
import scipy as sc

In [29]:
im = Image.open('Galaxy.jpg')
#im.show()
arr =  np.array(im)
print arr
arr = np.ravel(arr)
print arr
print arr[3]
print arr[4]
print arr[5]

[[[26 21 25]
  [22 17 21]
  [19 14 18]
  ..., 
  [ 7  8 12]
  [ 7  8 12]
  [14 15 19]]

 [[23 18 22]
  [21 16 20]
  [19 14 18]
  ..., 
  [13 14 18]
  [ 9 10 14]
  [ 6  7 11]]

 [[20 15 19]
  [20 15 19]
  [20 15 19]
  ..., 
  [14 15 19]
  [15 16 20]
  [15 16 20]]

 ..., 
 [[11 11 11]
  [ 7  7  7]
  [ 2  2  2]
  ..., 
  [17 12 16]
  [18 13 17]
  [19 14 18]]

 [[13 13 13]
  [ 8  8  8]
  [ 2  2  2]
  ..., 
  [17 12 16]
  [18 13 17]
  [19 14 18]]

 [[21 10 16]
  [11  9 12]
  [ 0  4  5]
  ..., 
  [14  9 13]
  [18 12 16]
  [16 10 14]]]
[26 21 25 ..., 16 10 14]
22
17
21


In [1]:

pixels = list(im.getdata())
width, height = im.size
pixel = [pixels[i * width:(i+1) * width] for i in xrange(height)]


NameError: name 'im' is not defined

In [43]:
import numpy as np
pixel = np.asarray(pixel)
type(pixel)
pixel.shape
pixel.squeeze(pixel)

TypeError: only length-1 arrays can be converted to Python scalars

In [20]:
import pandas as pd
df = pd.DataFrame(all_pixels, columns = list('Galaxy_1'))
#df.append(all_pixels, columns=list('Galaxy_1'))

ValueError: Shape of passed values is (3, 1281280), indices imply (8, 1281280)